birthdate = input("Enter your Birth Date: ")
print(birthdate)
birthmonth = input("Enter your Birth Month: ")
print(birthmonth)
birthyear = input("Enter your Birth Year: ")
print(birthyear)
print("Your Birthday: " + birthdate + "-" + birthmonth + "-" + birthyear)
currentdate = input("Enter current date: ")
print(currentdate)
currentmonth = input("Enter current month: ")
print(currentmonth)
currentyear = input("Enter current year: ")
print("Current date: "+ currentdate + "-" + currentmonth + "-" + currentyear)

Current_age = int(currentyear) - int(birthyear)
print("*" * 25)
print("Your Current age is: ", Current_age)
print("*" * 25)
print("Coded by jabedkhanjb")
print("Visit me: https://allmylinks.com/jabedkhanjb")